version: "3.9"

services:
    nginx:
        image: nginx:latest
        container_name: irakli_nginx
        ports:
            - "8080:80"
        volumes:
            - "./app/files/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./app/src:/var/www/html"
