version: "3.9"

services:
    nginx:
        image: nginx:latest
        container_name: irakli_nginx
        ports:
            - "8080:80"
        volumes:
            - "./app/files/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./app/src:/var/www/html"
        links:
            - phpfpm
    phpfpm:
        build: "./app/"
        container_name: irakli_php
        volumes:
            - "./app/src:/var/www/html"
        links:
            - postgres
    postgres:
        image: postgres:15.2  # Compatible with MacBook M1
        container_name: irakli_postgres
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
        ports:
            - "5432:5432"
        volumes:
            - "./data:/var/lib/postgresql/data"
