version: "3.9"

services:
    nginx:
        image: nginx:latest
        container_name: irakli_nginx
        ports:
            - "8080:80"
        volumes:
            - "./app/files/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./app/src:/var/www/html"
        links:
            - phpfpm
    phpfpm:
        build: "./app/"
        container_name: irakli_php
        volumes:
            - "./app/src:/var/www/html"
#        links:
#            - postgres
#    postgres:
#        image: postgres:15.2  # Works on MacBook M1
#        container_name: irakli_postgres
#        environment:
#            POSTGRES_DB: test_db
#            POSTGRES_USER: test
#            POSTGRES_PASSWORD: test
#        ports:
#            - "5432:5432"
#        volumes:
#            - "./data:/var/lib/postgresql/data"
#    pgadmin:
#        image: dpage/pgadmin4:latest
#        container_name: irakli_pgadmin
#        environment:
#            PGADMIN_DEFAULT_EMAIL: irakli@example.com
#            PGADMIN_DEFAULT_PASSWORD: test
#            PGADMIN_LISTEN_PORT: 80
#        ports:
#            - "8081:80"
#        volumes:
#            - "./data:/var/lib/pgadmin"
#        depends_on:
#            - postgres
#        links:
#            - postgres
#    mongodb:
#        image: mongo:5.0
#        container_name: irakli_mongodb
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: example
#        ports:
#            - 27018:27017
#    mongoexpress:
#        image: mongo-express:latest
#        container_name: irakli_mongoexpress
#        restart: always
##        restart: unless-stopped
#        ports:
#            - 8082:8081
#        environment:
#            ME_CONFIG_MONGODB_ADMINUSERNAME: root
#            ME_CONFIG_MONGODB_ADMINPASSWORD: example
#            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
##            ME_CONFIG_MONGODB_SERVER: mongodb
#        depends_on:
#            - mongodb
#        links:
#            - mongodb
    mongodb:
        # https://hub.docker.com/_/mongo/
        image: mongo:3.6
        container_name: irakli_mongo
        restart: always
        platform: linux/amd64
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: mongouser
    #      MONGO_INITDB_ROOT_PASSWORD: secret
    #      MONGO_INITDB_DATABASE: mongo_testing
        volumes:
#            - mongo_data:/data/db
            - "./mongo/data:/data/db"
            - "./mongo/config:/data/configdb"
#            - mongo_config:/data/configdb
#          - ./fixtures:/fixtures
            - ./scripts:/docker-entrypoint-initdb.d
        ports:
            - 27018:27017

#volumes:
##    mongo_data:
#    mongo_config:

